--- #YAML:1.0
name:                WebService-CRUST
version:             0.1
abstract:            A lightweight Client for making REST calls
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::Simple:                  0.44
    XML::Simple:                   2.16
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chris Heschong (chris@wiw.org)
